config/routes.rb
Rails.application.routes.draw do
  resources :propiedads
  devise_for :users
  resources :propietarios
  resources :idiomas
  get 'home/index'

  resources :clientes

  root to: 'home#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :idiomas
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:name, :description, :nif, :address, :city, :telephone, :email)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<div class="container">

  <%= form_for(@cliente) do |f| %>
    <% if @cliente.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

        <ul>
        <% @cliente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, "Nombre" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :apellidos, "Apellidos" %><br>
      <%= f.text_field :apellidos, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description, "Descripción" %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :nif, "NIF" %><br>
      <%= f.text_field :nif, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :address, "Dirección" %><br>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :city, "Ciudad" %><br>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :telephone, "Teléfono" %><br>
      <%= f.number_field :telephone, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "E-mail" %><br>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= f.submit class:"btn btn-primary" %>
      </div>
      <div class="col-sm-6">
        <%= link_to 'Atrás', clientes_path, class:"btn btn-primary-outline" %>
      </div>
    </div>
  <% end %>

</div>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form' %>

app/views/clientes/index.html.erb
<h1>Listado de Clientes</h1>
<%= link_to "Nuevo Cliente +", new_cliente_path, class: "btn btn-primary amc-button-margin" %>
<br>

<div class="table-responsive">

  <table class="table table-striped">
    <thead class="thead-inverse">
      <tr>
        <th>Nombre</th>
        <th>Apelidos</th>
        <th>Descripción</th>
        <th>NIF</th>
        <th>Dirección</th>
        <th>Ciudad</th>
        <th>Teléfono</th>
        <th>E-mail</th>
        <th class="amc_centrar" colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @clientes.each do |cliente| %>
        <tr>
          <td><%= link_to cliente.name, cliente_path(cliente) %></td>
          <td><%= link_to cliente.apellidos, cliente_path(cliente) %></td>
          <td><%= cliente.description %></td>
          <td><%= cliente.nif %></td>
          <td><%= cliente.address %></td>
          <td><%= cliente.city %></td>
          <td><%= cliente.telephone %></td>
          <td><%= cliente.email %></td>
          <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
          <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>  <!-- End of table-responsive -->

<br>

<%= link_to "Nuevo Cliente +", new_cliente_path, class: "btn btn-primary", id: "my-id" %>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form' %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cliente.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cliente.description %>
</p>

<p>
  <strong>Nif:</strong>
  <%= @cliente.nif %>
</p>

<p>
  <strong>Address:</strong>
  <%= @cliente.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @cliente.city %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @cliente.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>