config/routes.rb
Rails.application.routes.draw do
  resources :propiedads
  devise_for :users
  resources :propietarios
  resources :idiomas
  get 'home/index'

  resources :clientes

  root to: 'home#index'

end

app/models/propietario.rb
class Propietario < ActiveRecord::Base
end

app/controllers/propietarios_controller.rb
class PropietariosController < ApplicationController
  before_action :set_propietario, only: [:show, :edit, :update, :destroy]

  # GET /propietarios
  # GET /propietarios.json
  def index
    @propietarios = Propietario.all
  end

  # GET /propietarios/1
  # GET /propietarios/1.json
  def show
  end

  # GET /propietarios/new
  def new
    @propietario = Propietario.new
  end

  # GET /propietarios/1/edit
  def edit
  end

  # POST /propietarios
  # POST /propietarios.json
  def create
    @propietario = Propietario.new(propietario_params)

    respond_to do |format|
      if @propietario.save
        format.html { redirect_to @propietario, notice: 'Propietario was successfully created.' }
        format.json { render :show, status: :created, location: @propietario }
      else
        format.html { render :new }
        format.json { render json: @propietario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /propietarios/1
  # PATCH/PUT /propietarios/1.json
  def update
    respond_to do |format|
      if @propietario.update(propietario_params)
        format.html { redirect_to @propietario, notice: 'Propietario was successfully updated.' }
        format.json { render :show, status: :ok, location: @propietario }
      else
        format.html { render :edit }
        format.json { render json: @propietario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /propietarios/1
  # DELETE /propietarios/1.json
  def destroy
    @propietario.destroy
    respond_to do |format|
      format.html { redirect_to propietarios_url, notice: 'Propietario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_propietario
      @propietario = Propietario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def propietario_params
      params.require(:propietario).permit(:name, :apellidos, :nif, :email, :telephone, :telephone2, :asesor, :asesor_id)
    end
end

app/helpers/propietarios_helper.rb
module PropietariosHelper
end

app/views/propietarios/_form.html.erb
<div class="container">

  <%= form_for(@propietario) do |f| %>
    <% if @propietario.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@propietario.errors.count, "error") %> prohibited this propietario from being saved:</h2>

        <ul>
        <% @propietario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, "Nombre" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :apellidos, "Apellidos" %><br>
      <%= f.text_field :apellidos, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :nif, "NIF" %><br>
      <%= f.text_field :nif, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "E-mail" %><br>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :telephone, "Teléfono" %><br>
      <%= f.text_field :telephone, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :telephone2 %><br>
      <%= f.text_field :telephone2, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :asesor, "Asesor" %><br>
      <%= f.text_field :asesor, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :asesor_id, "ID Asesor" %><br>
      <%= f.text_field :asesor_id, class: "form-control" %>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= f.submit class:"btn btn-primary" %>
      </div>
      <div class="col-sm-6">
        <%= link_to 'Atrás', propietarios_path, class:"btn btn-primary-outline" %>
      </div>
    </div>
  <% end %>

</div>

app/views/propietarios/edit.html.erb
<h1>Editar Propietario</h1>

<%= render 'form' %>

app/views/propietarios/index.html.erb
<h1>Listado de Propietarios</h1>
<%= link_to "Nuevo Propietario +", new_propietario_path, class: "btn btn-primary amc-button-margin" %>
<br>

<div class="table-responsive">

  <table class="table table-striped">
    <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Apellidos</th>
        <th>Nif</th>
        <th>Email</th>
        <th>Telephone</th>
        <th>Telephone2</th>
        <th>Asesor</th>
        <th>Asesor</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @propietarios.each do |propietario| %>
        <tr>
          <td><%= link_to propietario.name, propietario_path(propietario) %></td>
          <td><%= link_to propietario.apellidos, propietario_path(propietario) %></td>
          <td><%= propietario.nif %></td>
          <td><%= propietario.email %></td>
          <td><%= propietario.telephone %></td>
          <td><%= propietario.telephone2 %></td>
          <td><%= propietario.asesor %></td>
          <td><%= propietario.asesor_id %></td>
          <td><%= link_to 'Editar', edit_propietario_path(propietario) %></td>
          <td><%= link_to 'Eliminar', propietario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div> <!-- End of table-responsive -->

<br>

<%= link_to "Nuevo Propietario +", new_propietario_path, class: "btn btn-primary", id: "my-id" %>

app/views/propietarios/new.html.erb
<h1>Nuevo Propietario</h1>

<%= render 'form' %>

app/views/propietarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @propietario.name %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @propietario.apellidos %>
</p>

<p>
  <strong>Nif:</strong>
  <%= @propietario.nif %>
</p>

<p>
  <strong>Email:</strong>
  <%= @propietario.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @propietario.telephone %>
</p>

<p>
  <strong>Telephone2:</strong>
  <%= @propietario.telephone2 %>
</p>

<p>
  <strong>Asesor:</strong>
  <%= @propietario.asesor %>
</p>

<p>
  <strong>Asesor:</strong>
  <%= @propietario.asesor_id %>
</p>

<%= link_to 'Edit', edit_propietario_path(@propietario) %> |
<%= link_to 'Back', propietarios_path %>