config/routes.rb
Rails.application.routes.draw do
  resources :propiedads
  devise_for :users
  resources :propietarios
  resources :idiomas
  get 'home/index'

  resources :clientes

  root to: 'home#index'

end

app/models/propiedad.rb
class Propiedad < ActiveRecord::Base
end

app/controllers/propiedads_controller.rb
class PropiedadsController < ApplicationController
  before_action :set_propiedad, only: [:show, :edit, :update, :destroy]

  # GET /propiedads
  # GET /propiedads.json
  def index
    @propiedads = Propiedad.all
  end

  # GET /propiedads/1
  # GET /propiedads/1.json
  def show
  end

  # GET /propiedads/new
  def new
    @propiedad = Propiedad.new
  end

  # GET /propiedads/1/edit
  def edit
  end

  # POST /propiedads
  # POST /propiedads.json
  def create
    @propiedad = Propiedad.new(propiedad_params)

    respond_to do |format|
      if @propiedad.save
        format.html { redirect_to @propiedad, notice: 'Propiedad was successfully created.' }
        format.json { render :show, status: :created, location: @propiedad }
      else
        format.html { render :new }
        format.json { render json: @propiedad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /propiedads/1
  # PATCH/PUT /propiedads/1.json
  def update
    respond_to do |format|
      if @propiedad.update(propiedad_params)
        format.html { redirect_to @propiedad, notice: 'Propiedad was successfully updated.' }
        format.json { render :show, status: :ok, location: @propiedad }
      else
        format.html { render :edit }
        format.json { render json: @propiedad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /propiedads/1
  # DELETE /propiedads/1.json
  def destroy
    @propiedad.destroy
    respond_to do |format|
      format.html { redirect_to propiedads_url, notice: 'Propiedad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_propiedad
      @propiedad = Propiedad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def propiedad_params
      params.require(:propiedad).permit(:tipo_operacion, :tipo_inmueble, :titulo, :subtitulo, :descripcion, :localizacion, :distrito, :direccion, :cod_postal, :precio_desde, :precio_hasta, :superficie_desde, :superficie_hasta, :estado, :ubicacion, :distrito, :dormitorios, :banos)
    end
end

app/helpers/propiedads_helper.rb
module PropiedadsHelper
end

app/views/propiedads/_form.html.erb
<%= form_for(@propiedad) do |f| %>
  <% if @propiedad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@propiedad.errors.count, "error") %> prohibited this propiedad from being saved:</h2>

      <ul>
      <% @propiedad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_operacion %><br>
    <%= f.text_field :tipo_operacion %>
  </div>
  <div class="field">
    <%= f.label :tipo_inmueble %><br>
    <%= f.text_field :tipo_inmueble %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :subtitulo %><br>
    <%= f.text_field :subtitulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :localizacion %><br>
    <%= f.text_field :localizacion %>
  </div>
  <div class="field">
    <%= f.label :distrito %><br>
    <%= f.text_field :distrito %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :cod_postal %><br>
    <%= f.text_field :cod_postal %>
  </div>
  <div class="field">
    <%= f.label :precio_desde %><br>
    <%= f.text_field :precio_desde %>
  </div>
  <div class="field">
    <%= f.label :precio_hasta %><br>
    <%= f.text_field :precio_hasta %>
  </div>
  <div class="field">
    <%= f.label :superficie_desde %><br>
    <%= f.text_field :superficie_desde %>
  </div>
  <div class="field">
    <%= f.label :superficie_hasta %><br>
    <%= f.text_field :superficie_hasta %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br>
    <%= f.text_field :ubicacion %>
  </div>
  <div class="field">
    <%= f.label :distrito %><br>
    <%= f.text_field :distrito %>
  </div>
  <div class="field">
    <%= f.label :dormitorios %><br>
    <%= f.number_field :dormitorios %>
  </div>
  <div class="field">
    <%= f.label :banos %><br>
    <%= f.number_field :banos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/propiedads/edit.html.erb
<h1>Editing Propiedad</h1>

<%= render 'form' %>

<%= link_to 'Show', @propiedad %> |
<%= link_to 'Back', propiedads_path %>

app/views/propiedads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Propiedads</h1>

<table>
  <thead>
    <tr>
      <th>Tipo operacion</th>
      <th>Tipo inmueble</th>
      <th>Titulo</th>
      <th>Subtitulo</th>
      <th>Descripcion</th>
      <th>Localizacion</th>
      <th>Distrito</th>
      <th>Direccion</th>
      <th>Cod postal</th>
      <th>Precio desde</th>
      <th>Precio hasta</th>
      <th>Superficie desde</th>
      <th>Superficie hasta</th>
      <th>Estado</th>
      <th>Ubicacion</th>
      <th>Distrito</th>
      <th>Dormitorios</th>
      <th>Banos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @propiedads.each do |propiedad| %>
      <tr>
        <td><%= propiedad.tipo_operacion %></td>
        <td><%= propiedad.tipo_inmueble %></td>
        <td><%= propiedad.titulo %></td>
        <td><%= propiedad.subtitulo %></td>
        <td><%= propiedad.descripcion %></td>
        <td><%= propiedad.localizacion %></td>
        <td><%= propiedad.distrito %></td>
        <td><%= propiedad.direccion %></td>
        <td><%= propiedad.cod_postal %></td>
        <td><%= propiedad.precio_desde %></td>
        <td><%= propiedad.precio_hasta %></td>
        <td><%= propiedad.superficie_desde %></td>
        <td><%= propiedad.superficie_hasta %></td>
        <td><%= propiedad.estado %></td>
        <td><%= propiedad.ubicacion %></td>
        <td><%= propiedad.distrito %></td>
        <td><%= propiedad.dormitorios %></td>
        <td><%= propiedad.banos %></td>
        <td><%= link_to 'Show', propiedad %></td>
        <td><%= link_to 'Edit', edit_propiedad_path(propiedad) %></td>
        <td><%= link_to 'Destroy', propiedad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Propiedad', new_propiedad_path %>

app/views/propiedads/new.html.erb
<h1>New Propiedad</h1>

<%= render 'form' %>

<%= link_to 'Back', propiedads_path %>

app/views/propiedads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo operacion:</strong>
  <%= @propiedad.tipo_operacion %>
</p>

<p>
  <strong>Tipo inmueble:</strong>
  <%= @propiedad.tipo_inmueble %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @propiedad.titulo %>
</p>

<p>
  <strong>Subtitulo:</strong>
  <%= @propiedad.subtitulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @propiedad.descripcion %>
</p>

<p>
  <strong>Localizacion:</strong>
  <%= @propiedad.localizacion %>
</p>

<p>
  <strong>Distrito:</strong>
  <%= @propiedad.distrito %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @propiedad.direccion %>
</p>

<p>
  <strong>Cod postal:</strong>
  <%= @propiedad.cod_postal %>
</p>

<p>
  <strong>Precio desde:</strong>
  <%= @propiedad.precio_desde %>
</p>

<p>
  <strong>Precio hasta:</strong>
  <%= @propiedad.precio_hasta %>
</p>

<p>
  <strong>Superficie desde:</strong>
  <%= @propiedad.superficie_desde %>
</p>

<p>
  <strong>Superficie hasta:</strong>
  <%= @propiedad.superficie_hasta %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @propiedad.estado %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @propiedad.ubicacion %>
</p>

<p>
  <strong>Distrito:</strong>
  <%= @propiedad.distrito %>
</p>

<p>
  <strong>Dormitorios:</strong>
  <%= @propiedad.dormitorios %>
</p>

<p>
  <strong>Banos:</strong>
  <%= @propiedad.banos %>
</p>

<%= link_to 'Edit', edit_propiedad_path(@propiedad) %> |
<%= link_to 'Back', propiedads_path %>